name: Vincent Tsang
url: http://example.org
description: Vince's blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
